# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87a558c623f455f8f923ec23b50865873bd731a29f002b958c4bf12993f5067673a6d478e119a87599b4be39da2841fbe78a70989c92681b3028d8ffa978bf69

test:
  secret_key_base: 7cec8953ab9c8481812927f81e01b1028dbd458224b0340d9fb180dc555ad67fb701f291368d4b0b1f47728301f572b9bbaeb802a4bfdd2f002b8313cb23b7c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
